### ISSUE TITLE
Competitive - (both) Leaderboards formating

### ISSUE THREAD

**Issue by GrotheFAF** [FAForever/website#96]
With smaller width it looks like this:
![faf-website-leaderboards](https://cloud.githubusercontent.com/assets/19195504/26799300/45262eda-4a35-11e7-9eba-e437d982ff1b.jpg)
and even smaller it looks like this:
![faf-website-leaderboards2](https://cloud.githubusercontent.com/assets/19195504/26799329/689545ae-4a35-11e7-9822-231218fc59ba.jpg)

**Comment by Raistlfiren** [comment]
This should be fixed. Please reopen this issue if it isn't.

**Comment by GrotheFAF** [comment]
no, not fixed, looks the same. (checked with firefox)

I can't reopen this, no buttom (no rights?)

**Comment by Raistlfiren** [comment]
@GrotheFAF It isn't live yet. Please check - https://test.faforever.com/

**Comment by GrotheFAF** [comment]
on test... it looks ok.

(finer note: the center-formation in name-selection dropdown, seems counter intuitive to me.)

**Comment by GrotheFAF** [comment]
on test... it looks ok.

I can't get a result with 'enter', I have to select a name from the dropdown, is that intentional?
(finer note: the center-formation in name-selection dropdown, seems counter intuitive to me.)

**Comment by Raistlfiren** [comment]
@GrotheFAF - It is intentional, but it probably isn't intuitive. I may look at changing that along with left aligning of the text.

**Comment by Raistlfiren** [comment]
Thank you @GrotheFAF

**Comment by Raistlfiren** [comment]
@GrotheFAF - Can you look at test.faforever.com and see if this covers your issues that you had problems with. 

Thanks!

**Comment by GrotheFAF** [comment]
looks good.

(I was wondering, why I don't show up as user in Globalrating -> Rating over 900.. that explains it ;-)

**Comment by Raistlfiren** [comment]
Thank you for checking that @GrotheFAF! 👍
